### ISSUE TITLE
ping-pong app max rate too small

### ISSUE THREAD

**Issue by Kristoff-starling** [UWNetworksLab/adn-controller#28]
The maximum request rate of the frontend-ping edge is only ~1600 req/sec. One of the possible reason is that the frontend service outputs log info for every RPC, which makes IO cost the bottleneck of the whole system.

**Comment by Kristoff-starling** [comment]
@Romero027 as we are migrating to new machines, maybe it's the right time to comment the log info and push a new image to dockerhub :)

**Comment by Romero027** [comment]
Hmm, is this one replica or multiple replicas?

**Comment by Kristoff-starling** [comment]
Will use multiple replicas as the default configuration. Close as completed.
